[package]
name = "freqm"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
serde = { version = "1.0.106", features = ["derive"] }
csv = "1.1.3"
snafu = "0.6.6"
decimal = "2.0.4"
