[package]
name = "freqm"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2024"

[dependencies]
structopt = "0.3.13"
serde = { version = "1.0.106", features = ["derive"] }
csv = "1.1.3"
snafu = "0.8.5"
decimal = "2.0.4"
serial = "0.4"
camino = "1.1.9"
serialport = "4.7.1"
