// Supported by Kenwood supplied MCP (memory control program) software as an
// import format
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct ArrlTravelPlusRow {
    sequence_number: String,
    country: String,
    region: String,
    state: String,
    location: String,
    output_frequency: String,
    input_frequency: String,
    call_sign: String,
    repeater_notes: String,
    ctcss_tones: String,
    sponsor: String,
}

// Chrip format, offset based.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct ChirpRow {
    location: String,
    name: String,
    frequency: String,
    duplex: String,
    offset: String,
    tone: String,
    r_tone_freq: String,
    c_tone_freq: String,
    dtcs_code: String,
    dtcs_polarity: String,
    rx_dtcs_code: String,
    cross_mode: String,
    mode: String,
    t_step: String,
    skip: String,
    power: String,
    comment: String,
    ur_call: String,
    rpt1_call: String,
    rpt2_call: String,
    dv_code: String,
}

// tsv (tab seperated)
// Wn	World Region	Cn	Country	Gn	Group	Callsign	Gateway	Lockout	Name	Sub Name	Frequency	Shift	Offset	Mode	Uplink Tone	Downlink Tone	Position	Lat DD	Lat MM.mm	N/S	Lon DDD	Lon MM.mm	E/W	Time Zone	TH-D74A	TH-D74E	TH-D74	Aux 1	Aux 2	Aux 3
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct KenwoodTh74aRow {
    wn: String,
    world_region: String,
    cn: String,
    country: String,
    gn: String,
    group: String,
    callsign: String,
    gateway: String,
    lockout: String,
    name: String,
    sub_name: String,
    frequency: String,
    shift: String,
    offset: String,
    mode: String,
    uplink_tone: String,
    downlink_tone: String,
    position: String,
    lat_dd: String,
    lat_mm_mm: String,
    n_s: String,
    lon_ddd: String,
    lon_mm_mm: String,
    e_w: String,
    time_zone: String,
}

/// Boston Marathon ICS (Incident Command System) format, exported from the PDF using Tabula
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct BostonMarathonIcsRow {
    ch_number: String,
    function: String,
    channel_name: String,
    assignment: String,
    rx_freq_wn: String,
    rx_tone_nac: String,
    tx_freq_wn: String,
    tx_tone_nac: String,
    mode_a_or_d: String,
    remarks: String,
}

/// CPS MD-UV390 format, exported from the CPS software
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct Uv390Row {
    channel_mode: String,
    channel_name: String,
    rx_freq_mhz: String,
    tx_freq_mhz: String,
    band_width: String,
    scan_list: String,
    squelch: String,
    rx_ref_freq: String,
    tx_ref_freq: String,
    tot_s: String,
    tot_rekey_delay_s: String,
    power: String,
    admit_criteria: String,
    auto_scan: String,
    rx_only: String,
    lone_worker: String,
    vox: String,
    allow_talkaround: String,
    send_gps_info: String,
    recv_gps_info: String,
    private_call_confirmed: String,
    emergency_alarm_ack: String,
    data_call_confirmed: String,
    allow_interrupt: String,
    dcdm_switch: String,
    leader_ms: String,
    emergency_system: String,
    contact_name: String,
    group_list: String,
    color_code: String,
    repeater_slot: String,
    in_call_criteria: String,
    privacy: String,
    privacy_number: String,
    gps_system: String,
    ctcss_dcs_dec: String,
    ctcss_dcs_enc: String,
    rx_signaling_system: String,
    tx_signaling_system: String,
    qt_reverse: String,
    non_qt_dqt_turn_off_freq: String,
    display_ptt_id: String,
    reverse_burst_turn_off_code: String,
    decode_1: String,
    decode_2: String,
    decode_3: String,
    decode_4: String,
    decode_5: String,
    decode_6: String,
    decode_7: String,
    decode_8: String,
}
